---
DB:
  HOST: 'kbs-leb.com'
  PORT: 3306
  DATABASE: 'kbslb_portal'
  USERNAME: 'kbslb_db'
  PASSWORD: 'kbs2011Leb'

SITE:
  Template_Name: r3k
  ROOT_PATH: ''

SMTP:
  Host: 'smtp.office365.com'
  SMTPAuth: true
  Username: 'Rabih.kobaissy@outlook.com'
  Password: 'Rabih1984'
  Port: 587
  SMTPSecure: 'ENCRYPTION_STARTTLS'

GIT_ACCESS_TOKEN: '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'