on:  
  release:
    types: [published]
name: 🚀 Deploy website on release
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.funandeat.dk
        server-dir: '/relax.funneat.dk/'
        username: support@funandeat.dk
        password: ${{ secrets.ftp_password2 }}
        exclude: |
          **/.git*
          **/.git*/**
          **/.vscode*/**
          **/node_modules/**
